{{- if .Values.monitor.create }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.clusterName }}-grafana
  labels:
    app: {{ .Values.clusterName }}-monitor
spec:
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: {{ .Values.monitor.grafana.service.type }}
  selector:
    app: {{ .Values.clusterName }}-monitor
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.clusterName }}-prometheus
  labels:
    app: {{ .Values.clusterName }}-monitor
spec:
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  type: {{ .Values.monitor.prometheus.service.type }}
  selector:
    app: {{ .Values.clusterName }}-monitor
{{- end }}
