{{- if .Values.monitor.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-grafana-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.monitor.grafana.username | default "admin" | b64enc }}
  password: {{ .Values.monitor.grafana.password | default "admin" | b64enc }}
{{- end }}
