{{- if .Values.monitor.create }}
{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Namespace }}:{{ .Values.clusterName }}-monitor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Namespace }}:{{ .Values.clusterName }}-monitor
subjects:
- kind: ServiceAccount
  name: {{ .Values.clusterName }}-monitor
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}:{{ .Values.clusterName }}-monitor
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.clusterName }}-monitor
{{- end }}
{{- end }}
