# Default values for tidb-operator
rbac:
  create: true

# operatorImage is TiDB Operator image
operatorImage: pingcap/tidb-operator:latest
imagePullPolicy: Always
defaultStorageClassName: standard

controllerManager:
  logLevel: 2
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 150Mi
    requests:
      cpu: 80m
      memory: 50Mi

