# Default values for tidb-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterName: demo-cluster

# services is the service list to expose, default is ClusterIP
# can be ClusterIP | NodePort | LoadBalancer
services:
  - name: pd
    type: ClusterIP
  - name: tidb
    type: NodePort

pd:
  replicas: 3
  image: uhub.ucloud.cn/pingcap/pd:v2.0.4
  logLevel: info
  # maxStoreDownTime is how long a store will be considered `down` when disconnected
  # if a store is considered `down`, the regions will be migrated to other stores
  maxStoreDownTime: 1h
  # maxReplicas is the number of replicas for each region
  maxReplicas: 3
  resources: {}
    # limits:
    #   cpu: 8000m
    #   memory: 8Gi
    # requests:
    #   cpu: 4000m
    #   memory: 4Gi
    #   storage: 1Gi
  # nodeSelector is used for scheduling pod,
  # if nodeSelectorRequired is true, all the following labels must be matched
  nodeSelector: {}
    # kind: pd
    # # zone is comma separated availability zone list
    # zone: cn-bj1-01,cn-bj1-02
    # # region is comma separated region list
    # region: cn-bj1

tidb:
  replicas: 2
  image: uhub.ucloud.cn/pingcap/tidb:v2.0.4
  logLevel: info
  resources: {}
    # limits:
    #   cpu: 16000m
    #   memory: 16Gi
    # requests:
    #   cpu: 12000m
    #   memory: 12Gi
  nodeSelector: {}
    # kind: tidb
    # zone: cn-bj1-01,cn-bj1-02
    # region: cn-bj1
