# Default values for tidb-operator
rbac:
  create: true

# operatorImage is TiDB Operator image
operatorImage: localhost:5000/pingcap/tidb-operator:latest

defaultStorageClassName: pingcap-nfs

controllerManager:
  logLevel: 2
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 150Mi
    requests:
      cpu: 80m
      memory: 50Mi

